##############################################################################
# Medcat Worker Deployment
##############################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neulander-worker-medcat
  namespace: neulander
  labels:
    app: neulander-medcat_14
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neulander-medcat_14
  template:
    metadata:
      labels:
        app: neulander-medcat_14
    spec:
      containers:
      - name: medcat-container
        image: {{ .Values.containerRegistry }}/{{ .Values.medcat.image.name }}:{{ .Values.medcat.image.tag }}
        imagePullPolicy: {{ .Values.api.image.pullPolicy }}
        ports:
        - containerPort: 8000
        env:
          - name: RABBITMQ_HOST
            valueFrom:
              secretKeyRef:
                name: neulander-rmq-default-user
                key: host
          - name: RABBITMQ_PORT
            valueFrom:
              secretKeyRef:
                name: neulander-rmq-default-user
                key: port
          - name: RABBITMQ_USER
            valueFrom:
              secretKeyRef:
                name: neulander-rmq-nondefault-user
                key: username
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: neulander-rmq-nondefault-user
                key: password
          - name: RABBITMQ_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: neulander-rmq-nondefault-user
                key: connection_string
          - name: MEDCAT_MODEL_PATH
            value: {{ .Values.medcat.medcatModelPath }}
          {{- if eq .Values.medcat.dummyMode true }}
          - name: DUMMY_MODE
            value: "true"
          {{- end }}
        resources:
        {{- if eq .Values.medcat.dummyMode true }}
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"
        {{ else }}
            {{- toYaml .Values.medcat.resources | nindent 12 }}
        {{ end -}}
        # livenessProbe:
        #   httpGet:
        #     path: /liveness
        #     port: 8000
        #   initialDelaySeconds: 30
        #   periodSeconds: 60
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8000
        #   initialDelaySeconds: 30
        #   periodSeconds: 60