apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: neulander
  namespace: neulander
spec:
  tags:
  - policymaker
  # - administrator
  rabbitmqClusterReference:
    name: neulander-rmq
  importCredentialsSecret:
    name: neulander-rmq-nondefault-user
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: neulander-permission
  namespace: neulander
spec:
  vhost: "/"
  user: "neulander" # name of the RabbitMQ user
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: neulander-rmq
