##############################################################################
# API Deployment
##############################################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: neulander-api
  labels:
    xlscsde.nhs.uk/app: neulander-api
spec:
  replicas: 2
  selector:
    matchLabels:
      xlscsde.nhs.uk/app: neulander-api
  template:
    metadata:
      labels:
        xlscsde.nhs.uk/app: neulander-api
    spec:
      containers:
        - name: api
          image: {{ .Values.registryUrl}}/{{ .Values.api.image.name }}:{{ .Values.api.image.tag }}
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.rabbitmq.host.secret }}
                  key: {{ .Values.rabbitmq.host.secretKey }}
            - name: RABBITMQ_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.rabbitmq.port.secret }}
                  key: {{ .Values.rabbitmq.port.secretKey }}
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.rabbitmq.user.secret }}
                  key: {{.Values.rabbitmq.user.secretKey }}
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.rabbitmq.password.secret }}
                  key: {{ .Values.rabbitmq.password.secretKey }}
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.api.apiKey.secret }}
                  key: {{ .Values.api.apiKey.secretKey }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 60
