##############################################################################
# API service
##############################################################################

apiVersion: v1
kind: Service
metadata:
  name: neulander-api
  
  labels:
    xlscsde.nhs.uk/app: neulander-api
spec:
  selector:
    xlscsde.nhs.uk/app: neulander-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
  type: ClusterIP