##############################################################################
# API Deployment
##############################################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: neulander-api
  namespace: neulander
  labels:
    app: neulander-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: neulander-api
  template:
    metadata:
      labels:
        app: neulander-api
    spec:
      containers:
        - name: api
          image: "my-repo/my-api:latest"
          ports:
            - containerPort: 8000
          env:
            - name: ENVIRONMENT
              value: "production"
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"

##############################################################################
# API service
##############################################################################

apiVersion: v1
kind: Service
metadata:
  name: neulander-api
  namespace: neulander
  labels:
    app: neulander-api
spec:
  selector:
    app: neulander-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP