{{- range queue := .Values.rabbitmq.queues }}
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: {{ queue.name }} # name of this custom resource; does not have to the same as the actual queue name
  namespace: neulander
spec:
  name: queue-todo # name of the queue
  autoDelete: false
  durable: true
  rabbitmqClusterReference:
    name: nlp-cluster