{{- with .Values.rabbitmq  -}}
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: neulander-rabbit
  annotations:
    rabbitmq.com/topology-allowed-namespaces: {{ .allowedNamespaces }}
    {{- with .annotations }}
    {{- toYaml .annotations | nindent 4 }}
    {{- end }}
spec:
  service:
    type: ClusterIP
  replicas: {{ .replicaCount }}
  resources:
    {{- toYaml .resources | nindent 4 }}
  rabbitmq:
    additionalConfig: {{toString .additionalConfig }}
{{- end }}