apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: neulander-rmq
  namespace: neulander
  annotations:
    rabbitmq.com/topology-allowed-namespaces: neulander
spec:
  service:
    type: ClusterIP
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: neulander
  namespace: neulander
spec:
  tags:
  - policymaker
  # - administrator
  rabbitmqClusterReference:
    name: neulander-rmq
  importCredentialsSecret:
    name: neulander-rmq-nondefault-user
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: neulander-permission
  namespace: neulander
spec:
  vhost: "/"
  user: "neulander" # name of the RabbitMQ user
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: neulander-rmq
