kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: neulander-medcat-storage
  labels:
    xlscsde.nhs.uk/app: neulander-medcat_14
spec:
  accessModes:
    {{ toYaml .Values.medcat.storage.accessModes | nindent 4 }}
  volumeMode: Filesystem
  storageClassName: {{ .Values.medcat.storage.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.medcat.storage.size }}

    
