##############################################################################
# API Deployment
##############################################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: neulander-api
  namespace: neulander
  labels:
    app: neulander-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: neulander-api
  template:
    metadata:
      labels:
        app: neulander-api
    spec:
      containers:
        - name: api
          image: {{ .Values.containerRegistry }}/{{ .Values.api.image.name }}:{{ .Values.api.image.tag }}
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: neulander-rmq-default-user
                  key: host
            - name: RABBITMQ_PORT
              valueFrom:
                secretKeyRef:
                  name: neulander-rmq-default-user
                  key: port
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: neulander-rmq-nondefault-user
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: neulander-rmq-nondefault-user
                  key: password
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: neulander-api
                  key: api-key            
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 60